- .gitignore
- authenticator/authenticator.go
- authenticator/go.mod
- authenticator/go.sum
- authenticator/protos/authenticator.pb.go
- authenticator/protos/authenticator.proto
- docker-compose.yml
- sdk/Dockerfile
- sdk/python/approzium/__init__.py
- sdk/python/approzium/_psycopg2_ctypes.py
- sdk/python/approzium/authenticator.py
- sdk/python/approzium/iam.py
- sdk/python/approzium/misc.py
- sdk/python/approzium/pg_scram.pyx
- sdk/python/approzium/protos/authenticator_pb2.py
- sdk/python/approzium/protos/authenticator_pb2_grpc.py
- sdk/python/approzium/psycopg2.py
- sdk/python/client.py
- sdk/python/setup.py
- ssl/Dockerfile
- ssl/aios_gen_cert.sh
Main feature:
- Implement SCRAM SHA-256 authentication on Authenticator and Python SDK sides.
- Implement appropriate module-level logging in Python SDK
Minor features:
- Add SSL support to Postgres docker image (useful for testing)
- Introduce two Postgres services in docker-compose (one that uses MD5, the other uses SHA-256)
- Make Authenticator be able to hold multiple dev credentials (to be able to simultaneously test said databases)
- Refactor SDK Psycopg2 connection code (move low-level functions to _psycopg2_ctypes.py)
- Copy scram implementation file from Asyncpg source code (with modifications to fit our use case)
> Implement SCRAM SHA-256 Authentication

- sdk/python/approzium/_psycopg2_ctypes.py
- sdk/python/approzium/psycopg2.py
libpq seems to only support the OpenSSL API, based on the fact that it directly references it in its documentation. Based on [this discussion](https://www.postgresql.org/message-id/96dabede-e72a-b51f-13b9-c8d85216a7f0%40iki.fi) It seems that other libraries could try to implement that API.
We just load whatever `ssl` library the system is setup to find first. Therefore, it is possible we load a different library or version thereof than the one libpq is using. If libpq is using a different version, we expect that issues might happen. However, this is also the case with Psycopg2, which [might segfault](https://github.com/psycopg/psycopg2/issues/543). Therefore, we conclude that we do not add extra risk. 
As some sort of check, we ensure that libpq is indeed using OpenSSL and otherwise we …
> Add check for openssl

- authenticator/authenticator.go
- authenticator/go.mod
- authenticator/main.go
This PR updates the authenticator's package name to fix `$ go get`, which was giving the following output previously:
```
$ go get github.com/approzium/approzium/authenticator
go: finding github.com/approzium/approzium latest
go: finding github.com/approzium/approzium/authenticator latest
go get: github.com/approzium/approzium/authenticator@v0.0.0-20200617171948-73c36c013a1b: parsing go.mod:
module declares its path as: approzium/authenticator
but was required as: github.com/approzium/approzium/authenticator
```
> Update package name

- authenticator/authenticator.go
- authenticator/go.mod
- authenticator/main.go
Just a super quick update from snake case to camel case because Go uses [mixed caps](https://golang.org/doc/effective_go.html#mixed-caps) for variable naming.
> Convert variables from snake case to camel case

- sdk/python/approzium/_psycopg2_ctypes.py
Previously innocuous code started failing due to SyntaxError when we updated to using Python 3.7
> Fix: Stop using async because it becomes SyntaxError in Python>=3.7

- .github/workflows/main.yml
- authenticator/authenticator.go
- authenticator/authenticator_test.go
- sdk/python/.flake8
- sdk/python/approzium/__init__.py
- sdk/python/approzium/_psycopg2_ctypes.py
- sdk/python/approzium/_psycopg2_scram.py
- sdk/python/approzium/authenticator.py
- sdk/python/approzium/iam.py
- sdk/python/approzium/misc.py
- sdk/python/approzium/protos/authenticator_pb2.py
- sdk/python/approzium/protos/authenticator_pb2_grpc.py
- sdk/python/approzium/psycopg2.py
- sdk/python/client.py
- sdk/python/pyproject.toml
- sdk/python/setup.py
- sdk/python/tests/run_pg2_testsuite.py
- sdk/python/tests/test_approzium_sdk.py
- Fixes many style errors such that CI lint stage passes (except for a Syntax error that is handled in #42 
- Add `pyproject.toml` and `.flake8` files for configuring style checkers
> Python style fixes and a Go Unittest for xorBytes

- Dockerfile
- Makefile
Using `pytest-parallel` plugin, we get a little speed up in running tests. For example, 9.2 sec vs 18.6 sec running on Github Actions. Will be helpful too when we add more tests in the future.
> Run Python tests in parallel

- README.md
- sdk/python/approzium/authenticator.py
- sdk/python/approzium/iam.py
Previously, if a `TEST_IAM_ARN` wasn't provided, we failed. This PR adds support for not providing one.
If a test ARN isn't provided, we will now execute one `GetCallerIdentity` on our side to learn our ARN locally to populate the `claimed_arn`. We will also construct a signed `GetCallerIdentity` request to pass on to the Go `Authenticator`. 
When I test this locally, it results in my personal user ARN being detected by the `boto3` library and passed on to the `Authenticator`. It pulls credentials as documented [here](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html).
> Add automatic ARN determination

- README.md
- authenticator/go.mod
- authenticator/go.sum
- authenticator/main.go
- authenticator/main_test.go
- docker-compose.test.yml
- docker-compose.yml
- docs/src/pages/api-docs/python-sdk.mdx
- docs/src/pages/examples.mdx
- docs/src/pages/overview.mdx
- docs/src/pages/quickstart_.mdx
- sdk/python/examples/asyncpg_client.py
- sdk/python/examples/asyncpg_pool.py
- sdk/python/examples/pg2_client.py
- sdk/python/examples/pg2_pool.py
- sdk/python/tests/run_pg2_testsuite.py
- sdk/python/tests/test_asyncpg_connect.py
- sdk/python/tests/test_psycopg2_connect.py
This PR adds support for configuring the local address, local port, and log level through environment variables.
I thought about adding Vault configuration at this level too, but I didn't because there are multiple, and they may change over time. Instead, I documented what's needed.
This PR also slightly changes how the logs look from:
To:
This was based on personal preference and what I've seen elsewhere. However, I'm quite flexible on this and can change it back if desired. :-)
> Support config through env variables

- docs/src/pages/languages/python.mdx
- docs/src/pages/overview.mdx
- docs/src/pages/quickstart_.mdx
Closes #15 
This PR documents the AWS environments the Python client is confirmed to work in. 
It also updates the Vault docs, and elaborates on granting access through `iam_arns`.
> Include AWS platforms in docs

- authenticator/main.go
- authenticator/server/authenticator.go
- authenticator/server/authenticator_test.go
- authenticator/server/config.go
- authenticator/server/credmgrs/credmgr.go
- authenticator/server/credmgrs/hc_vault.go
- authenticator/server/credmgrs/hc_vault_test.go
- docs/src/pages/quickstart_.mdx
This PR adds support for pulling a Vault token from a file. This will prevent its Vault access from expiring when the original `VAULT_TOKEN` pulled at startup expires.
The Vault agent pushes tokens out to file and always keeps them updated. It can be used with a variety of platforms, not just AWS, so this will be forward-compatible with the other ones we add as well.
> Add support for using a Vault token sink file

- docs/Makefile
- sdk/python/approzium/_authenticator.py
In addition to title, fixed a tiny bug where if the IAM arn is automatically determined, it is not shown in `attribution_info`
> Add JSON attribution_info to authenticator

- Makefile
This fixes the flaky test failure we've been seeing:
```
=== RUN TestFuzzAuthenticator 
race: limit on 8128 simultaneously alive goroutines is exceeded, dying 
FAIL	github.com/approzium/approzium/authenticator/server	15.740s
```
None of the tests by themselves have more than 2,000 goroutines going at once. However, by default, Go runs tests in parallel. So, the reason we're seeing this failure is that when the tests are run in parallel, they can at times have that many goroutines going.
This PR solves that by setting the Go test parallelism to 1, which prevents that many goroutines from going at once. I've run the tests remotely 10 times and haven't seen the problem again.
> Fix flaky test

- .github/workflows/main.yml
- sdk/python/approzium/asyncpg/_asyncpg_connect.py
- sdk/python/approzium/psycopg2/_psycopg2_connect.py
- sdk/python/tests/run_pg2_testsuite.py
- sdk/python/tests/test_asyncpg_connect.py
- sdk/python/tests/test_psycopg2_connect.py
Looks like `isort` just had a new major release which broke the interface we use. This updates the command in our CI to stay compatible.
To avoid having these issues in the future, this PR also specifies the versions of the lint tools used, so pip will install the latest compatible patch version.
> Fix isort change in Github actions workflow

- authenticator/server/authenticator_test.go
- authenticator/server/testing/testutil.go
This PR skips a flaky test I attempted to fix in #91 but is still failing on the `develop` branch. The test succeeds locally, and it succeeds in PR, but it fails when merged into `develop`. Rather than continue to have the failures, I've moved it to be behind an acceptance test flag.
> Skip flaky fuzzing test

- sdk/python/approzium/psycopg2/_psycopg2_connect.py
- sdk/python/approzium/psycopg2/_psycopg2_ctypes.py
The problem was that we told Python to find the `libpq` (the C library used by Psycopg2) by specifying its name directly as `libpq.so.5`. However, this name is only correct on Linux and could differ by OS. For example, on OSX this would be `libpq.5.dylib` and Windows uses `.dll`. The fix is to use a function that finds the library by name on whatever OS Python is running on.
> Fix running approzium.psycopg2 on OSX

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
This repo wasn't picking up our feature request and bug report templates due to us moving, so I went through the process of reconfiguring them. This results in a minor change adding labels to the pre-created templates.
> Auto-label issue templates

- sdk/python/docs/source/examples.rst
Updates the paths of examples in Sphinx source files so that they show up in the resulting HTML
> Fix examples paths in Sphinx

- Dockerfile
- docker-compose.yml
- Change `build` image into `authenticator-build` which does not have self-signed certs and is the image we publish, and `authenticator-dev` which has certs and is used in tests.
> Create authenticator docker image for deployment

- authenticator/Makefile
- authenticator/README.md
- authenticator/main.go
- authenticator/server/config/config.go
- authenticator/server/config/config_test.go
Closes #126 
I've also added a note to our release instructions to manually bump the version number each time.
```
➜  authenticator git:(develop) authenticator --version
Approzium v0.1.1
```
```
➜  authenticator git:(develop) authenticator --dev
INFO   [2020-07-14T10:42:28-07:00] api starting on https://127.0.0.1:6000
INFO   [2020-07-14T10:42:32-07:00] loading secrets at "/Users/rebeccapetrin/go/src/github.com/cyralinc/approzium/authenticator/server/testing/secrets.yaml"
INFO   [2020-07-14T10:42:32-07:00] secrets loaded, please restart authenticator to load edits
INFO   [2020-07-14T10:42:32-07:00] selected local file as credential manager
WARNING[2020-07-14T10:42:32-07:00] local file credential manager should not be used in production
INFO   [2020-07-14T10:42:32-07:00] grpc starting on …
```
> Add --version and --dev flags

- sdk/python/approzium/_authenticator.py
- sdk/python/examples/psycopg2_connect.py
- Fixed issue where having `disable_tls=True` when instantiating an AuthClient still required a TLSconfig argument.
- Fixed error when running example by setting the default auth client instead of passing it in.
> Fix non-TLS Connection to Authenticator

- docs/src/theme/CodeBlock/index.js
By default, "keywords" (like `from` and `import` in python) are italicized by the code highlighting package ([Prism](https://prismjs.com/)), but I thought it looked a bit unnatural. What do y'all think?
Original
With change
> unitalicize keywords in code blocks

- .github/SECURITY.md
- README.md
Adds a doc on reporting security issues to `.github/SECURITY.md`. This
allows GitHub to display information on how to report such issues.
When creating an Issue or PR, GitHub will present links to this security
policy. The policy is also accessible from the Security tab on the main
page of the repo.
This mostly just moves the existing information in the README to the
appropriate location for this GitHub feature.
Here are some screenshots of this GitHub feature.
With the SECURITY.md file in place, GitHub will display the contents of the Markdown file in this section.
> docs: Add GitHub Security Policy

- authenticator/server/config/config.go
On my branch, I noticed I'd marked the command-line TLS flag as the wrong type.
> Fix TLS flag

- docs/docs/quickstart.mdx
- sdk/python/docs/source/userguide.rst
By default, the SDK does not install all of its supported database drivers. However, for ease of use, they could be installed using pip optional features, which allow us to run `pip3 install approzium[sqllibs]` or `pip3 install approzium[tracing]`. The first command is the one used in the quickstart, and the more detailed explanation is in the Python SDK user guide.
closes #162
> Clarify Docs for Installing Database Drivers Alongside SDK

- docs/docs/quickstart.mdx
Closes #161 
This PR improves our instructions on how to download the authenticator binary, making them much more specific so it'll be easier for people wanting to try it out.
> Give direct authenticator instructions

- .github/workflows/lint.yml
- authenticator/server/authenticator.go
- authenticator/server/config/config.go
- authenticator/server/credmgrs/hc_vault.go
- authenticator/server/credmgrs/local_file.go
- authenticator/server/identity/aws.go
in addition to title, this PR includes some fixes to the code (and where appropriate, gosec "ignore" annotations ) to appease gosec's checks.
Thanks to Daniel Tobin's [blogpost](https://cyral.com/blog/security-as-code-implementing-lint-and-gosec/) for bringing this tool to my attention.
> Add gosec Security Checks to CI

- .github/workflows/release.yml
- authenticator/.goreleaser.yml
This adds a workflow that runs on tags that start with "v". Currently, it has just one step that automatically generates the authenticator binaries. See this test release (on a fork) for an [example of what it looks like.](https://github.com/UpGado/approzium/releases/tag/v0.0.0)
Python SDK and authenticator Docker image publishing are added, but I couldn't think of a good approach for testing those beyond the "production"/real world environment.
> Add Releasing to CI

- docs/yarn.lock
This PR updates the `jpeg-js` dependency in our docs site, which should resolve the security error raised by dependabot.
> Update docs/jpeg-js to ^0.4.0

- authenticator/main.go
- authenticator/server/config/config.go
- authenticator/server/credmgrs/aws_secrets_manager.go
- docs/docs/configuration.mdx
This PR is from testing AWS Secrets Manager, and is intended to be merged into our 0.2.0 release branch. It:
- Fixes a bug I found where I had, in code, named a file section `secrets_manager` but in docs I'd called it `secrets`. 
- Increases documentation around AWS Secrets Manager.
- Bumps the Approzium version in another place I found.
- Adds the ability for the Approzium authenticator to assume a role, which made it easier to test and also will give users more flexibility around how a role is acquired.
> Updates from testing AWS Secrets Manager

- .gitignore
- docs/docs/deployment.mdx
- docs/docs/installation.mdx
- sdk/python/README.md
- terraform/aws/approzium.config.yml
- terraform/aws/main.tf
- terraform/aws/scripts/install.sh.tpl
- terraform/aws/variables.tf
This PR has updates I found from testing our Terraform deploy script with Terraform 0.12.29. I ran `terraform plan` and `terraform apply`, and validated that an Approzium instance came up with the Authenticator running as configured.
These changes are intended to be included in the 0.2.0 release.
> Updates from testing Terraform

- authenticator/server/config/config.go
This PR adds a user-friendly **description** field for each config parameter. This results in an improvement to the command-line help experience, which formerly only listed the names of the fields with no further description.
This PR is intended to be included in 0.2.0.
```
➜  authenticator git:(config-help-improvements) ✗ authenticator -h
Usage of authenticator:
listener
-host string
The address at which Approzium's authenticator should run.
-http-port int
The port that should serve HTTP traffic.
-grpc-port int
The port that should serve GRPC traffic, used for client authentication requests.
tls
-disable-tls bool
Set to true to disable TLS encryption. Not recommended in production environments.
-tls-cert-path string
The path to the certificate proving the Approzium authenticator's …
```
> Improve command-line usage

- docs/docs/quickstart.mdx
- sql_driver.go
This PR adds a pass-through file in the `github.com/cyralinc/approzium` home directory.
This allows the actual SDK to continue living in `github.com/cyralinc/approzium/sdk/go/approzium`, but it enables a more idiomatic experience for Go developers where they'll be able to do the following:
- `go get github.com/cyralinc/approzium`
- `import "github.com/cyralinc/approzium"`
> Make Go SDK available from home directory

- authenticator/server/api/health.go
- authenticator/server/api/health_test.go
Make it so the health check endpoint returns a body like {"server_time_utc": "2020-09-25T16:08:11Z", "version": "0.9.1"}.
> Make the health check endpoint return more information

- README.md
- authenticator/server/identity/aws.go
This PR is in relation to [this article](https://googleprojectzero.blogspot.com/2020/10/enter-the-vault-auth-issues-hashicorp-vault.html) describing a security vulnerability in Vault. 
We have similar code, so I checked it through and found that we're actually **not** vulnerable to the same issue because we have been checking the `Action` header all along. Just in case, though, I decided to tighten up checking what's in the response we get from AWS to make sure it doesn't have an unexpected content-type header. Also, just in case there's some other header that we don't know about that could be used to slip in JSON, I added a check to make sure the body doesn't look like it could contain JSON.
> Increase response verification

- .github/workflows/lint.yml
- docs/yarn.lock
Fixes transitive dependencies vulnerabilities by addressing the following dependabot PRs:
- #238
- #239
- #241
- #242
This commit also fixes an error with the `lint` workflow by updating the `black` formatter library to version `22.3.0`.
> Fix dependencies vulnerabilities and lint workflow

- docs/package.json
- docs/yarn.lock
All the vulnerabilities classified as `high` or `critical` were solved.
The following packages were upgraded to the following versions:
- `node-fetch`: 2.6.4
- `cross-fetch`: 3.1.15
- `async`: 2.6.7
- `trim`:  0.0.3
These changes were done by changing  the `docs/yarn.lock` file directly, however, for `trim` upgrade it demands the inclusion of the field "resolutions"  at `docs/package.json`.
> CGS-411: Security fixes for npm dependencies
